# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2852e07e740b191db780647fbb2387d16ca8721b41cf4e73fa3427c0ad72a6cb666b204687c39217c08842ea8d7942ba14efbed7c32033cc87f16a687b92a16e

test:
  secret_key_base: e01af69e5cf9cdf0ce091abff1cbdfa63f573610b156162c2aa6bec976c4f9a93da578aeb101965d98ace1c6ede47f7c4d82457cf33c68f8aee52f90f12d1e26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
